name: SJVAN
favicon: null
layout_spectrum: 0.5806015292182565
typography_spectrum: 0.17632292257621884
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.12473596073687077
  lightness: 0.8464333100710064
  saturation: 0.992096908390522
  rhythmicContrast: 0.7227797727100551
purpose: []
